apiVersion: v1
kind: Pod
metadata:
  name: containerproxy
  labels:
    ci: containerproxy-build
spec:
  containers:
    - name: containerproxy-build
      image: public.ecr.aws/docker/library/maven:3-eclipse-temurin-21-jammy
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "2"
