/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FetchServiceStatus200Response
 */
@JsonPropertyOrder({
  FetchServiceStatus200Response.JSON_PROPERTY_SYSTEM$GET_SERVICE_STATUS
})
@JsonTypeName("fetchServiceStatus_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class FetchServiceStatus200Response {
  public static final String JSON_PROPERTY_SYSTEM$GET_SERVICE_STATUS = "system$get_service_status";
  @javax.annotation.Nullable
  private String system$getServiceStatus;

  public FetchServiceStatus200Response() {
  }

  public FetchServiceStatus200Response system$getServiceStatus(@javax.annotation.Nullable String system$getServiceStatus) {
    
    this.system$getServiceStatus = system$getServiceStatus;
    return this;
  }

  /**
   * Get system$getServiceStatus
   * @return system$getServiceStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYSTEM$GET_SERVICE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystem$getServiceStatus() {
    return system$getServiceStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_SYSTEM$GET_SERVICE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystem$getServiceStatus(@javax.annotation.Nullable String system$getServiceStatus) {
    this.system$getServiceStatus = system$getServiceStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FetchServiceStatus200Response fetchServiceStatus200Response = (FetchServiceStatus200Response) o;
    return Objects.equals(this.system$getServiceStatus, fetchServiceStatus200Response.system$getServiceStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(system$getServiceStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FetchServiceStatus200Response {\n");
    sb.append("    system$getServiceStatus: ").append(toIndentedString(system$getServiceStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

