/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GrantOf
 */
@JsonPropertyOrder({
  GrantOf.JSON_PROPERTY_CREATED_ON,
  GrantOf.JSON_PROPERTY_ROLE,
  GrantOf.JSON_PROPERTY_GRANTED_TO,
  GrantOf.JSON_PROPERTY_GRANTEE_NAME,
  GrantOf.JSON_PROPERTY_GRANTED_BY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class GrantOf {
  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  @javax.annotation.Nullable
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private String role;

  public static final String JSON_PROPERTY_GRANTED_TO = "granted_to";
  @javax.annotation.Nullable
  private String grantedTo;

  public static final String JSON_PROPERTY_GRANTEE_NAME = "grantee_name";
  @javax.annotation.Nullable
  private String granteeName;

  public static final String JSON_PROPERTY_GRANTED_BY = "granted_by";
  @javax.annotation.Nullable
  private String grantedBy;

  public GrantOf() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public GrantOf(
    @JsonProperty(JSON_PROPERTY_CREATED_ON) OffsetDateTime createdOn, 
    @JsonProperty(JSON_PROPERTY_ROLE) String role, 
    @JsonProperty(JSON_PROPERTY_GRANTED_TO) String grantedTo, 
    @JsonProperty(JSON_PROPERTY_GRANTEE_NAME) String granteeName, 
    @JsonProperty(JSON_PROPERTY_GRANTED_BY) String grantedBy
  ) {
    this();
    this.createdOn = createdOn;
    this.role = role;
    this.grantedTo = grantedTo;
    this.granteeName = granteeName;
    this.grantedBy = grantedBy;
  }

  /**
   * Date and time when the grant was created
   * @return createdOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  /**
   * The name of the service role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRole() {
    return role;
  }



  /**
   * The type of the grantee, can be USER or ROLE
   * @return grantedTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTED_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrantedTo() {
    return grantedTo;
  }



  /**
   * The name of the grantee
   * @return granteeName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTEE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGranteeName() {
    return granteeName;
  }



  /**
   * The name of role that granted the service role to the grantee
   * @return grantedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrantedBy() {
    return grantedBy;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrantOf grantOf = (GrantOf) o;
    return Objects.equals(this.createdOn, grantOf.createdOn) &&
        Objects.equals(this.role, grantOf.role) &&
        Objects.equals(this.grantedTo, grantOf.grantedTo) &&
        Objects.equals(this.granteeName, grantOf.granteeName) &&
        Objects.equals(this.grantedBy, grantOf.grantedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, role, grantedTo, granteeName, grantedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrantOf {\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    grantedTo: ").append(toIndentedString(grantedTo)).append("\n");
    sb.append("    granteeName: ").append(toIndentedString(granteeName)).append("\n");
    sb.append("    grantedBy: ").append(toIndentedString(grantedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

