/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * A Snowflake job service object.
 */
@JsonPropertyOrder({
  JobService.JSON_PROPERTY_NAME,
  JobService.JSON_PROPERTY_STATUS,
  JobService.JSON_PROPERTY_COMPUTE_POOL,
  JobService.JSON_PROPERTY_SPEC,
  JobService.JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS,
  JobService.JSON_PROPERTY_QUERY_WAREHOUSE,
  JobService.JSON_PROPERTY_COMMENT,
  JobService.JSON_PROPERTY_IS_ASYNC_JOB
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class JobService {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_COMPUTE_POOL = "compute_pool";
  @javax.annotation.Nonnull
  private String computePool;

  public static final String JSON_PROPERTY_SPEC = "spec";
  @javax.annotation.Nonnull
  private ServiceSpec spec;

  public static final String JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS = "external_access_integrations";
  @javax.annotation.Nullable
  private List<String> externalAccessIntegrations = new ArrayList<>();

  public static final String JSON_PROPERTY_QUERY_WAREHOUSE = "query_warehouse";
  @javax.annotation.Nullable
  private String queryWarehouse;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @javax.annotation.Nullable
  private String comment;

  public static final String JSON_PROPERTY_IS_ASYNC_JOB = "is_async_job";
  @javax.annotation.Nullable
  private Boolean isAsyncJob;

  public JobService() {
  }

  public JobService name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public JobService status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The current status of the service.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public JobService computePool(@javax.annotation.Nonnull String computePool) {
    
    this.computePool = computePool;
    return this;
  }

  /**
   * Specifies the name of the compute pool in your account on which to run the service.
   * @return computePool
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPUTE_POOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getComputePool() {
    return computePool;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPUTE_POOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComputePool(@javax.annotation.Nonnull String computePool) {
    this.computePool = computePool;
  }

  public JobService spec(@javax.annotation.Nonnull ServiceSpec spec) {
    
    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   * @return spec
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SPEC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServiceSpec getSpec() {
    return spec;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpec(@javax.annotation.Nonnull ServiceSpec spec) {
    this.spec = spec;
  }

  public JobService externalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    
    this.externalAccessIntegrations = externalAccessIntegrations;
    return this;
  }

  public JobService addExternalAccessIntegrationsItem(String externalAccessIntegrationsItem) {
    if (this.externalAccessIntegrations == null) {
      this.externalAccessIntegrations = new ArrayList<>();
    }
    this.externalAccessIntegrations.add(externalAccessIntegrationsItem);
    return this;
  }

  /**
   * Specifies the names of the external access integrations that allow your service to access external sites.
   * @return externalAccessIntegrations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExternalAccessIntegrations() {
    return externalAccessIntegrations;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    this.externalAccessIntegrations = externalAccessIntegrations;
  }

  public JobService queryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    
    this.queryWarehouse = queryWarehouse;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return queryWarehouse
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueryWarehouse() {
    return queryWarehouse;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    this.queryWarehouse = queryWarehouse;
  }

  public JobService comment(@javax.annotation.Nullable String comment) {
    
    this.comment = comment;
    return this;
  }

  /**
   * Specifies a comment for the service.
   * @return comment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }

  public JobService isAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    
    this.isAsyncJob = isAsyncJob;
    return this;
  }

  /**
   * True if the service is an async job service; false otherwise.
   * @return isAsyncJob
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ASYNC_JOB, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsAsyncJob() {
    return isAsyncJob;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ASYNC_JOB, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    this.isAsyncJob = isAsyncJob;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobService jobService = (JobService) o;
    return Objects.equals(this.name, jobService.name) &&
        Objects.equals(this.status, jobService.status) &&
        Objects.equals(this.computePool, jobService.computePool) &&
        Objects.equals(this.spec, jobService.spec) &&
        Objects.equals(this.externalAccessIntegrations, jobService.externalAccessIntegrations) &&
        Objects.equals(this.queryWarehouse, jobService.queryWarehouse) &&
        Objects.equals(this.comment, jobService.comment) &&
        Objects.equals(this.isAsyncJob, jobService.isAsyncJob);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, computePool, spec, externalAccessIntegrations, queryWarehouse, comment, isAsyncJob);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobService {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    computePool: ").append(toIndentedString(computePool)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    externalAccessIntegrations: ").append(toIndentedString(externalAccessIntegrations)).append("\n");
    sb.append("    queryWarehouse: ").append(toIndentedString(queryWarehouse)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isAsyncJob: ").append(toIndentedString(isAsyncJob)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

