/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QueryStatus
 */
@JsonPropertyOrder({
  QueryStatus.JSON_PROPERTY_CODE,
  QueryStatus.JSON_PROPERTY_SQL_STATE,
  QueryStatus.JSON_PROPERTY_MESSAGE,
  QueryStatus.JSON_PROPERTY_STATEMENT_HANDLE,
  QueryStatus.JSON_PROPERTY_CREATED_ON,
  QueryStatus.JSON_PROPERTY_STATEMENT_STATUS_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class QueryStatus {
  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_SQL_STATE = "sqlState";
  @javax.annotation.Nullable
  private String sqlState;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_STATEMENT_HANDLE = "statementHandle";
  @javax.annotation.Nonnull
  private UUID statementHandle;

  public static final String JSON_PROPERTY_CREATED_ON = "createdOn";
  @javax.annotation.Nullable
  private Long createdOn;

  public static final String JSON_PROPERTY_STATEMENT_STATUS_URL = "statementStatusUrl";
  @javax.annotation.Nullable
  private URI statementStatusUrl;

  public QueryStatus() {
  }

  public QueryStatus code(@javax.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }

  public QueryStatus sqlState(@javax.annotation.Nullable String sqlState) {
    
    this.sqlState = sqlState;
    return this;
  }

  /**
   * Get sqlState
   * @return sqlState
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SQL_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSqlState() {
    return sqlState;
  }


  @JsonProperty(value = JSON_PROPERTY_SQL_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
  }

  public QueryStatus message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public QueryStatus statementHandle(@javax.annotation.Nonnull UUID statementHandle) {
    
    this.statementHandle = statementHandle;
    return this;
  }

  /**
   * Get statementHandle
   * @return statementHandle
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATEMENT_HANDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getStatementHandle() {
    return statementHandle;
  }


  @JsonProperty(value = JSON_PROPERTY_STATEMENT_HANDLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatementHandle(@javax.annotation.Nonnull UUID statementHandle) {
    this.statementHandle = statementHandle;
  }

  public QueryStatus createdOn(@javax.annotation.Nullable Long createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Timestamp that specifies when the statement execution started. The timestamp is expressed in milliseconds since the epoch.
   * @return createdOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
  }

  public QueryStatus statementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    
    this.statementStatusUrl = statementStatusUrl;
    return this;
  }

  /**
   * URL that you can use to check the status of the execution of the statement and the result set.
   * @return statementStatusUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATEMENT_STATUS_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getStatementStatusUrl() {
    return statementStatusUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_STATEMENT_STATUS_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryStatus queryStatus = (QueryStatus) o;
    return Objects.equals(this.code, queryStatus.code) &&
        Objects.equals(this.sqlState, queryStatus.sqlState) &&
        Objects.equals(this.message, queryStatus.message) &&
        Objects.equals(this.statementHandle, queryStatus.statementHandle) &&
        Objects.equals(this.createdOn, queryStatus.createdOn) &&
        Objects.equals(this.statementStatusUrl, queryStatus.statementStatusUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, sqlState, message, statementHandle, createdOn, statementStatusUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryStatus {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    sqlState: ").append(toIndentedString(sqlState)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statementHandle: ").append(toIndentedString(statementHandle)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    statementStatusUrl: ").append(toIndentedString(statementStatusUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

