/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResultSetResultSetMetaDataPartitionInfoInner
 */
@JsonPropertyOrder({
  ResultSetResultSetMetaDataPartitionInfoInner.JSON_PROPERTY_ROW_COUNT,
  ResultSetResultSetMetaDataPartitionInfoInner.JSON_PROPERTY_COMPRESSED_SIZE,
  ResultSetResultSetMetaDataPartitionInfoInner.JSON_PROPERTY_UNCOMPRESSED_SIZE
})
@JsonTypeName("ResultSet_resultSetMetaData_partitionInfo_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataPartitionInfoInner {
  public static final String JSON_PROPERTY_ROW_COUNT = "rowCount";
  @javax.annotation.Nullable
  private Long rowCount;

  public static final String JSON_PROPERTY_COMPRESSED_SIZE = "compressedSize";
  @javax.annotation.Nullable
  private Long compressedSize;

  public static final String JSON_PROPERTY_UNCOMPRESSED_SIZE = "uncompressedSize";
  @javax.annotation.Nullable
  private Long uncompressedSize;

  public ResultSetResultSetMetaDataPartitionInfoInner() {
  }

  public ResultSetResultSetMetaDataPartitionInfoInner rowCount(@javax.annotation.Nullable Long rowCount) {
    
    this.rowCount = rowCount;
    return this;
  }

  /**
   * Number of rows in the partition.
   * minimum: 0
   * @return rowCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROW_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getRowCount() {
    return rowCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ROW_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRowCount(@javax.annotation.Nullable Long rowCount) {
    this.rowCount = rowCount;
  }

  public ResultSetResultSetMetaDataPartitionInfoInner compressedSize(@javax.annotation.Nullable Long compressedSize) {
    
    this.compressedSize = compressedSize;
    return this;
  }

  /**
   * the partition size before the decompression. This may or may not be present in the partitionInfo. Uncompressed size would always be there.
   * minimum: 0
   * @return compressedSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPRESSED_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCompressedSize() {
    return compressedSize;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPRESSED_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompressedSize(@javax.annotation.Nullable Long compressedSize) {
    this.compressedSize = compressedSize;
  }

  public ResultSetResultSetMetaDataPartitionInfoInner uncompressedSize(@javax.annotation.Nullable Long uncompressedSize) {
    
    this.uncompressedSize = uncompressedSize;
    return this;
  }

  /**
   * the partition size after the decompression
   * minimum: 0
   * @return uncompressedSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UNCOMPRESSED_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getUncompressedSize() {
    return uncompressedSize;
  }


  @JsonProperty(value = JSON_PROPERTY_UNCOMPRESSED_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUncompressedSize(@javax.annotation.Nullable Long uncompressedSize) {
    this.uncompressedSize = uncompressedSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataPartitionInfoInner resultSetResultSetMetaDataPartitionInfoInner = (ResultSetResultSetMetaDataPartitionInfoInner) o;
    return Objects.equals(this.rowCount, resultSetResultSetMetaDataPartitionInfoInner.rowCount) &&
        Objects.equals(this.compressedSize, resultSetResultSetMetaDataPartitionInfoInner.compressedSize) &&
        Objects.equals(this.uncompressedSize, resultSetResultSetMetaDataPartitionInfoInner.uncompressedSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowCount, compressedSize, uncompressedSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataPartitionInfoInner {\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    compressedSize: ").append(toIndentedString(compressedSize)).append("\n");
    sb.append("    uncompressedSize: ").append(toIndentedString(uncompressedSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

