/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * these stats might not be available for each request.
 */
@JsonPropertyOrder({
  ResultSetStats.JSON_PROPERTY_NUM_ROWS_INSERTED,
  ResultSetStats.JSON_PROPERTY_NUM_ROWS_UPDATED,
  ResultSetStats.JSON_PROPERTY_NUM_ROWS_DELETED,
  ResultSetStats.JSON_PROPERTY_NUM_DUPLICATE_ROWS_UPDATED
})
@JsonTypeName("ResultSet_stats")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetStats {
  public static final String JSON_PROPERTY_NUM_ROWS_INSERTED = "numRowsInserted";
  @javax.annotation.Nullable
  private Long numRowsInserted;

  public static final String JSON_PROPERTY_NUM_ROWS_UPDATED = "numRowsUpdated";
  @javax.annotation.Nullable
  private Long numRowsUpdated;

  public static final String JSON_PROPERTY_NUM_ROWS_DELETED = "numRowsDeleted";
  @javax.annotation.Nullable
  private Long numRowsDeleted;

  public static final String JSON_PROPERTY_NUM_DUPLICATE_ROWS_UPDATED = "numDuplicateRowsUpdated";
  @javax.annotation.Nullable
  private Long numDuplicateRowsUpdated;

  public ResultSetStats() {
  }

  public ResultSetStats numRowsInserted(@javax.annotation.Nullable Long numRowsInserted) {
    
    this.numRowsInserted = numRowsInserted;
    return this;
  }

  /**
   * Number of rows that were inserted.
   * minimum: 0
   * @return numRowsInserted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_INSERTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumRowsInserted() {
    return numRowsInserted;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_INSERTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumRowsInserted(@javax.annotation.Nullable Long numRowsInserted) {
    this.numRowsInserted = numRowsInserted;
  }

  public ResultSetStats numRowsUpdated(@javax.annotation.Nullable Long numRowsUpdated) {
    
    this.numRowsUpdated = numRowsUpdated;
    return this;
  }

  /**
   * Number of rows that were updated.
   * minimum: 0
   * @return numRowsUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumRowsUpdated() {
    return numRowsUpdated;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumRowsUpdated(@javax.annotation.Nullable Long numRowsUpdated) {
    this.numRowsUpdated = numRowsUpdated;
  }

  public ResultSetStats numRowsDeleted(@javax.annotation.Nullable Long numRowsDeleted) {
    
    this.numRowsDeleted = numRowsDeleted;
    return this;
  }

  /**
   * Number of rows that were deleted.
   * minimum: 0
   * @return numRowsDeleted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumRowsDeleted() {
    return numRowsDeleted;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumRowsDeleted(@javax.annotation.Nullable Long numRowsDeleted) {
    this.numRowsDeleted = numRowsDeleted;
  }

  public ResultSetStats numDuplicateRowsUpdated(@javax.annotation.Nullable Long numDuplicateRowsUpdated) {
    
    this.numDuplicateRowsUpdated = numDuplicateRowsUpdated;
    return this;
  }

  /**
   * Number of duplicate rows that were updated.
   * minimum: 0
   * @return numDuplicateRowsUpdated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_DUPLICATE_ROWS_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumDuplicateRowsUpdated() {
    return numDuplicateRowsUpdated;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_DUPLICATE_ROWS_UPDATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumDuplicateRowsUpdated(@javax.annotation.Nullable Long numDuplicateRowsUpdated) {
    this.numDuplicateRowsUpdated = numDuplicateRowsUpdated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetStats resultSetStats = (ResultSetStats) o;
    return Objects.equals(this.numRowsInserted, resultSetStats.numRowsInserted) &&
        Objects.equals(this.numRowsUpdated, resultSetStats.numRowsUpdated) &&
        Objects.equals(this.numRowsDeleted, resultSetStats.numRowsDeleted) &&
        Objects.equals(this.numDuplicateRowsUpdated, resultSetStats.numDuplicateRowsUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numRowsInserted, numRowsUpdated, numRowsDeleted, numDuplicateRowsUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetStats {\n");
    sb.append("    numRowsInserted: ").append(toIndentedString(numRowsInserted)).append("\n");
    sb.append("    numRowsUpdated: ").append(toIndentedString(numRowsUpdated)).append("\n");
    sb.append("    numRowsDeleted: ").append(toIndentedString(numRowsDeleted)).append("\n");
    sb.append("    numDuplicateRowsUpdated: ").append(toIndentedString(numDuplicateRowsUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

