/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataParameters;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataPartitionInfoInner;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaDataRowTypeInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResultSetResultSetMetaData
 */
@JsonPropertyOrder({
  ResultSetResultSetMetaData.JSON_PROPERTY_FORMAT,
  ResultSetResultSetMetaData.JSON_PROPERTY_NUM_ROWS,
  ResultSetResultSetMetaData.JSON_PROPERTY_ROW_TYPE,
  ResultSetResultSetMetaData.JSON_PROPERTY_PARTITION_INFO,
  ResultSetResultSetMetaData.JSON_PROPERTY_NULLABLE,
  ResultSetResultSetMetaData.JSON_PROPERTY_PARAMETERS
})
@JsonTypeName("ResultSet_resultSetMetaData")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaData {
  /**
   * For v2 endpoints the only possible value for this field is jsonv2.
   */
  public enum FormatEnum {
    JSONV2(String.valueOf("jsonv2"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nullable
  private FormatEnum format;

  public static final String JSON_PROPERTY_NUM_ROWS = "numRows";
  @javax.annotation.Nullable
  private Long numRows;

  public static final String JSON_PROPERTY_ROW_TYPE = "rowType";
  @javax.annotation.Nullable
  private List<ResultSetResultSetMetaDataRowTypeInner> rowType = new ArrayList<>();

  public static final String JSON_PROPERTY_PARTITION_INFO = "partitionInfo";
  @javax.annotation.Nullable
  private List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo = new ArrayList<>();

  public static final String JSON_PROPERTY_NULLABLE = "nullable";
  @javax.annotation.Nullable
  private Boolean nullable;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @javax.annotation.Nullable
  private ResultSetResultSetMetaDataParameters parameters;

  public ResultSetResultSetMetaData() {
  }

  public ResultSetResultSetMetaData format(@javax.annotation.Nullable FormatEnum format) {
    
    this.format = format;
    return this;
  }

  /**
   * For v2 endpoints the only possible value for this field is jsonv2.
   * @return format
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@javax.annotation.Nullable FormatEnum format) {
    this.format = format;
  }

  public ResultSetResultSetMetaData numRows(@javax.annotation.Nullable Long numRows) {
    
    this.numRows = numRows;
    return this;
  }

  /**
   * The total number of rows of results.
   * @return numRows
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getNumRows() {
    return numRows;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_ROWS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumRows(@javax.annotation.Nullable Long numRows) {
    this.numRows = numRows;
  }

  public ResultSetResultSetMetaData rowType(@javax.annotation.Nullable List<ResultSetResultSetMetaDataRowTypeInner> rowType) {
    
    this.rowType = rowType;
    return this;
  }

  public ResultSetResultSetMetaData addRowTypeItem(ResultSetResultSetMetaDataRowTypeInner rowTypeItem) {
    if (this.rowType == null) {
      this.rowType = new ArrayList<>();
    }
    this.rowType.add(rowTypeItem);
    return this;
  }

  /**
   * Get rowType
   * @return rowType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROW_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResultSetResultSetMetaDataRowTypeInner> getRowType() {
    return rowType;
  }


  @JsonProperty(value = JSON_PROPERTY_ROW_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRowType(@javax.annotation.Nullable List<ResultSetResultSetMetaDataRowTypeInner> rowType) {
    this.rowType = rowType;
  }

  public ResultSetResultSetMetaData partitionInfo(@javax.annotation.Nullable List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo) {
    
    this.partitionInfo = partitionInfo;
    return this;
  }

  public ResultSetResultSetMetaData addPartitionInfoItem(ResultSetResultSetMetaDataPartitionInfoInner partitionInfoItem) {
    if (this.partitionInfo == null) {
      this.partitionInfo = new ArrayList<>();
    }
    this.partitionInfo.add(partitionInfoItem);
    return this;
  }

  /**
   * Partition information
   * @return partitionInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARTITION_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ResultSetResultSetMetaDataPartitionInfoInner> getPartitionInfo() {
    return partitionInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_PARTITION_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPartitionInfo(@javax.annotation.Nullable List<ResultSetResultSetMetaDataPartitionInfoInner> partitionInfo) {
    this.partitionInfo = partitionInfo;
  }

  public ResultSetResultSetMetaData nullable(@javax.annotation.Nullable Boolean nullable) {
    
    this.nullable = nullable;
    return this;
  }

  /**
   * false if null is replaced with a string &#39;null&#39; otherwise false
   * @return nullable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NULLABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNullable() {
    return nullable;
  }


  @JsonProperty(value = JSON_PROPERTY_NULLABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
  }

  public ResultSetResultSetMetaData parameters(@javax.annotation.Nullable ResultSetResultSetMetaDataParameters parameters) {
    
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultSetResultSetMetaDataParameters getParameters() {
    return parameters;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameters(@javax.annotation.Nullable ResultSetResultSetMetaDataParameters parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaData resultSetResultSetMetaData = (ResultSetResultSetMetaData) o;
    return Objects.equals(this.format, resultSetResultSetMetaData.format) &&
        Objects.equals(this.numRows, resultSetResultSetMetaData.numRows) &&
        Objects.equals(this.rowType, resultSetResultSetMetaData.rowType) &&
        Objects.equals(this.partitionInfo, resultSetResultSetMetaData.partitionInfo) &&
        Objects.equals(this.nullable, resultSetResultSetMetaData.nullable) &&
        Objects.equals(this.parameters, resultSetResultSetMetaData.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, numRows, rowType, partitionInfo, nullable, parameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaData {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    numRows: ").append(toIndentedString(numRows)).append("\n");
    sb.append("    rowType: ").append(toIndentedString(rowType)).append("\n");
    sb.append("    partitionInfo: ").append(toIndentedString(partitionInfo)).append("\n");
    sb.append("    nullable: ").append(toIndentedString(nullable)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

