/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResultSetResultSetMetaDataRowTypeInner
 */
@JsonPropertyOrder({
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_NAME,
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_TYPE,
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_LENGTH,
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_PRECISION,
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_SCALE,
  ResultSetResultSetMetaDataRowTypeInner.JSON_PROPERTY_NULLABLE
})
@JsonTypeName("ResultSet_resultSetMetaData_rowType_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataRowTypeInner {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_LENGTH = "length";
  @javax.annotation.Nullable
  private Long length;

  public static final String JSON_PROPERTY_PRECISION = "precision";
  @javax.annotation.Nullable
  private Long precision;

  public static final String JSON_PROPERTY_SCALE = "scale";
  @javax.annotation.Nullable
  private Long scale;

  public static final String JSON_PROPERTY_NULLABLE = "nullable";
  @javax.annotation.Nullable
  private Boolean nullable;

  public ResultSetResultSetMetaDataRowTypeInner() {
  }

  public ResultSetResultSetMetaDataRowTypeInner name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ResultSetResultSetMetaDataRowTypeInner type(@javax.annotation.Nullable String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }

  public ResultSetResultSetMetaDataRowTypeInner length(@javax.annotation.Nullable Long length) {
    
    this.length = length;
    return this;
  }

  /**
   * Get length
   * minimum: 0
   * @return length
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLength() {
    return length;
  }


  @JsonProperty(value = JSON_PROPERTY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(@javax.annotation.Nullable Long length) {
    this.length = length;
  }

  public ResultSetResultSetMetaDataRowTypeInner precision(@javax.annotation.Nullable Long precision) {
    
    this.precision = precision;
    return this;
  }

  /**
   * Get precision
   * minimum: 0
   * @return precision
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRECISION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPrecision() {
    return precision;
  }


  @JsonProperty(value = JSON_PROPERTY_PRECISION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrecision(@javax.annotation.Nullable Long precision) {
    this.precision = precision;
  }

  public ResultSetResultSetMetaDataRowTypeInner scale(@javax.annotation.Nullable Long scale) {
    
    this.scale = scale;
    return this;
  }

  /**
   * Get scale
   * minimum: 0
   * @return scale
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCALE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getScale() {
    return scale;
  }


  @JsonProperty(value = JSON_PROPERTY_SCALE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScale(@javax.annotation.Nullable Long scale) {
    this.scale = scale;
  }

  public ResultSetResultSetMetaDataRowTypeInner nullable(@javax.annotation.Nullable Boolean nullable) {
    
    this.nullable = nullable;
    return this;
  }

  /**
   * Get nullable
   * @return nullable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NULLABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNullable() {
    return nullable;
  }


  @JsonProperty(value = JSON_PROPERTY_NULLABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNullable(@javax.annotation.Nullable Boolean nullable) {
    this.nullable = nullable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataRowTypeInner resultSetResultSetMetaDataRowTypeInner = (ResultSetResultSetMetaDataRowTypeInner) o;
    return Objects.equals(this.name, resultSetResultSetMetaDataRowTypeInner.name) &&
        Objects.equals(this.type, resultSetResultSetMetaDataRowTypeInner.type) &&
        Objects.equals(this.length, resultSetResultSetMetaDataRowTypeInner.length) &&
        Objects.equals(this.precision, resultSetResultSetMetaDataRowTypeInner.precision) &&
        Objects.equals(this.scale, resultSetResultSetMetaDataRowTypeInner.scale) &&
        Objects.equals(this.nullable, resultSetResultSetMetaDataRowTypeInner.nullable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, length, precision, scale, nullable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataRowTypeInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    precision: ").append(toIndentedString(precision)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("    nullable: ").append(toIndentedString(nullable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

