/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResultSetResultSetMetaDataParameters
 */
@JsonPropertyOrder({
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_BINARY_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_DATE_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_TIME_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT,
  ResultSetResultSetMetaDataParameters.JSON_PROPERTY_MULTI_STATEMENT_COUNT
})
@JsonTypeName("ResultSet_resultSetMetaData_parameters")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSetResultSetMetaDataParameters {
  public static final String JSON_PROPERTY_BINARY_OUTPUT_FORMAT = "binary_output_format";
  @javax.annotation.Nullable
  private String binaryOutputFormat;

  public static final String JSON_PROPERTY_DATE_OUTPUT_FORMAT = "date_output_format";
  @javax.annotation.Nullable
  private String dateOutputFormat;

  public static final String JSON_PROPERTY_TIME_OUTPUT_FORMAT = "time_output_format";
  @javax.annotation.Nullable
  private String timeOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT = "timestamp_output_format";
  @javax.annotation.Nullable
  private String timestampOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT = "timestamp_ltz_output_format";
  @javax.annotation.Nullable
  private String timestampLtzOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT = "timestamp_ntz_output_format";
  @javax.annotation.Nullable
  private String timestampNtzOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT = "timestamp_tz_output_format";
  @javax.annotation.Nullable
  private String timestampTzOutputFormat;

  public static final String JSON_PROPERTY_MULTI_STATEMENT_COUNT = "multi_statement_count";
  @javax.annotation.Nullable
  private Integer multiStatementCount;

  public ResultSetResultSetMetaDataParameters() {
  }

  public ResultSetResultSetMetaDataParameters binaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    
    this.binaryOutputFormat = binaryOutputFormat;
    return this;
  }

  /**
   * Get binaryOutputFormat
   * @return binaryOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BINARY_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBinaryOutputFormat() {
    return binaryOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_BINARY_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters dateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    
    this.dateOutputFormat = dateOutputFormat;
    return this;
  }

  /**
   * Get dateOutputFormat
   * @return dateOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateOutputFormat() {
    return dateOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters timeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    
    this.timeOutputFormat = timeOutputFormat;
    return this;
  }

  /**
   * Get timeOutputFormat
   * @return timeOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeOutputFormat() {
    return timeOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters timestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    
    this.timestampOutputFormat = timestampOutputFormat;
    return this;
  }

  /**
   * Get timestampOutputFormat
   * @return timestampOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampOutputFormat() {
    return timestampOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters timestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
    return this;
  }

  /**
   * Get timestampLtzOutputFormat
   * @return timestampLtzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampLtzOutputFormat() {
    return timestampLtzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters timestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
    return this;
  }

  /**
   * Get timestampNtzOutputFormat
   * @return timestampNtzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampNtzOutputFormat() {
    return timestampNtzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters timestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    
    this.timestampTzOutputFormat = timestampTzOutputFormat;
    return this;
  }

  /**
   * Get timestampTzOutputFormat
   * @return timestampTzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampTzOutputFormat() {
    return timestampTzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
  }

  public ResultSetResultSetMetaDataParameters multiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    
    this.multiStatementCount = multiStatementCount;
    return this;
  }

  /**
   * Get multiStatementCount
   * @return multiStatementCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MULTI_STATEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMultiStatementCount() {
    return multiStatementCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MULTI_STATEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSetResultSetMetaDataParameters resultSetResultSetMetaDataParameters = (ResultSetResultSetMetaDataParameters) o;
    return Objects.equals(this.binaryOutputFormat, resultSetResultSetMetaDataParameters.binaryOutputFormat) &&
        Objects.equals(this.dateOutputFormat, resultSetResultSetMetaDataParameters.dateOutputFormat) &&
        Objects.equals(this.timeOutputFormat, resultSetResultSetMetaDataParameters.timeOutputFormat) &&
        Objects.equals(this.timestampOutputFormat, resultSetResultSetMetaDataParameters.timestampOutputFormat) &&
        Objects.equals(this.timestampLtzOutputFormat, resultSetResultSetMetaDataParameters.timestampLtzOutputFormat) &&
        Objects.equals(this.timestampNtzOutputFormat, resultSetResultSetMetaDataParameters.timestampNtzOutputFormat) &&
        Objects.equals(this.timestampTzOutputFormat, resultSetResultSetMetaDataParameters.timestampTzOutputFormat) &&
        Objects.equals(this.multiStatementCount, resultSetResultSetMetaDataParameters.multiStatementCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(binaryOutputFormat, dateOutputFormat, timeOutputFormat, timestampOutputFormat, timestampLtzOutputFormat, timestampNtzOutputFormat, timestampTzOutputFormat, multiStatementCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSetResultSetMetaDataParameters {\n");
    sb.append("    binaryOutputFormat: ").append(toIndentedString(binaryOutputFormat)).append("\n");
    sb.append("    dateOutputFormat: ").append(toIndentedString(dateOutputFormat)).append("\n");
    sb.append("    timeOutputFormat: ").append(toIndentedString(timeOutputFormat)).append("\n");
    sb.append("    timestampOutputFormat: ").append(toIndentedString(timestampOutputFormat)).append("\n");
    sb.append("    timestampLtzOutputFormat: ").append(toIndentedString(timestampLtzOutputFormat)).append("\n");
    sb.append("    timestampNtzOutputFormat: ").append(toIndentedString(timestampNtzOutputFormat)).append("\n");
    sb.append("    timestampTzOutputFormat: ").append(toIndentedString(timestampTzOutputFormat)).append("\n");
    sb.append("    multiStatementCount: ").append(toIndentedString(multiStatementCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

