/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetResultSetMetaData;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ResultSetStats;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ResultSet
 */
@JsonPropertyOrder({
  ResultSet.JSON_PROPERTY_CODE,
  ResultSet.JSON_PROPERTY_SQL_STATE,
  ResultSet.JSON_PROPERTY_MESSAGE,
  ResultSet.JSON_PROPERTY_STATEMENT_HANDLE,
  ResultSet.JSON_PROPERTY_CREATED_ON,
  ResultSet.JSON_PROPERTY_STATEMENT_STATUS_URL,
  ResultSet.JSON_PROPERTY_RESULT_SET_META_DATA,
  ResultSet.JSON_PROPERTY_DATA,
  ResultSet.JSON_PROPERTY_STATS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ResultSet {
  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_SQL_STATE = "sqlState";
  @javax.annotation.Nullable
  private String sqlState;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_STATEMENT_HANDLE = "statementHandle";
  @javax.annotation.Nullable
  private UUID statementHandle;

  public static final String JSON_PROPERTY_CREATED_ON = "createdOn";
  @javax.annotation.Nullable
  private Long createdOn;

  public static final String JSON_PROPERTY_STATEMENT_STATUS_URL = "statementStatusUrl";
  @javax.annotation.Nullable
  private URI statementStatusUrl;

  public static final String JSON_PROPERTY_RESULT_SET_META_DATA = "resultSetMetaData";
  @javax.annotation.Nullable
  private ResultSetResultSetMetaData resultSetMetaData;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<List<String>> data = new ArrayList<>();

  public static final String JSON_PROPERTY_STATS = "stats";
  @javax.annotation.Nullable
  private ResultSetStats stats;

  public ResultSet() {
  }

  public ResultSet code(@javax.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }

  public ResultSet sqlState(@javax.annotation.Nullable String sqlState) {
    
    this.sqlState = sqlState;
    return this;
  }

  /**
   * Get sqlState
   * @return sqlState
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SQL_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSqlState() {
    return sqlState;
  }


  @JsonProperty(value = JSON_PROPERTY_SQL_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSqlState(@javax.annotation.Nullable String sqlState) {
    this.sqlState = sqlState;
  }

  public ResultSet message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public ResultSet statementHandle(@javax.annotation.Nullable UUID statementHandle) {
    
    this.statementHandle = statementHandle;
    return this;
  }

  /**
   * Get statementHandle
   * @return statementHandle
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATEMENT_HANDLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getStatementHandle() {
    return statementHandle;
  }


  @JsonProperty(value = JSON_PROPERTY_STATEMENT_HANDLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatementHandle(@javax.annotation.Nullable UUID statementHandle) {
    this.statementHandle = statementHandle;
  }

  public ResultSet createdOn(@javax.annotation.Nullable Long createdOn) {
    
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Timestamp that specifies when the statement execution started.‌ The timestamp is expressed in milliseconds since the epoch.‌
   * @return createdOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCreatedOn() {
    return createdOn;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedOn(@javax.annotation.Nullable Long createdOn) {
    this.createdOn = createdOn;
  }

  public ResultSet statementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    
    this.statementStatusUrl = statementStatusUrl;
    return this;
  }

  /**
   * Get statementStatusUrl
   * @return statementStatusUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATEMENT_STATUS_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getStatementStatusUrl() {
    return statementStatusUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_STATEMENT_STATUS_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatementStatusUrl(@javax.annotation.Nullable URI statementStatusUrl) {
    this.statementStatusUrl = statementStatusUrl;
  }

  public ResultSet resultSetMetaData(@javax.annotation.Nullable ResultSetResultSetMetaData resultSetMetaData) {
    
    this.resultSetMetaData = resultSetMetaData;
    return this;
  }

  /**
   * Get resultSetMetaData
   * @return resultSetMetaData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULT_SET_META_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultSetResultSetMetaData getResultSetMetaData() {
    return resultSetMetaData;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT_SET_META_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultSetMetaData(@javax.annotation.Nullable ResultSetResultSetMetaData resultSetMetaData) {
    this.resultSetMetaData = resultSetMetaData;
  }

  public ResultSet data(@javax.annotation.Nullable List<List<String>> data) {
    
    this.data = data;
    return this;
  }

  public ResultSet addDataItem(List<String> dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Result set data.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<List<String>> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<List<String>> data) {
    this.data = data;
  }

  public ResultSet stats(@javax.annotation.Nullable ResultSetStats stats) {
    
    this.stats = stats;
    return this;
  }

  /**
   * Get stats
   * @return stats
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultSetStats getStats() {
    return stats;
  }


  @JsonProperty(value = JSON_PROPERTY_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStats(@javax.annotation.Nullable ResultSetStats stats) {
    this.stats = stats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultSet resultSet = (ResultSet) o;
    return Objects.equals(this.code, resultSet.code) &&
        Objects.equals(this.sqlState, resultSet.sqlState) &&
        Objects.equals(this.message, resultSet.message) &&
        Objects.equals(this.statementHandle, resultSet.statementHandle) &&
        Objects.equals(this.createdOn, resultSet.createdOn) &&
        Objects.equals(this.statementStatusUrl, resultSet.statementStatusUrl) &&
        Objects.equals(this.resultSetMetaData, resultSet.resultSetMetaData) &&
        Objects.equals(this.data, resultSet.data) &&
        Objects.equals(this.stats, resultSet.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, sqlState, message, statementHandle, createdOn, statementStatusUrl, resultSetMetaData, data, stats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultSet {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    sqlState: ").append(toIndentedString(sqlState)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    statementHandle: ").append(toIndentedString(statementHandle)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    statementStatusUrl: ").append(toIndentedString(statementStatusUrl)).append("\n");
    sb.append("    resultSetMetaData: ").append(toIndentedString(resultSetMetaData)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

