/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceContainer
 */
@JsonPropertyOrder({
  ServiceContainer.JSON_PROPERTY_DATABASE_NAME,
  ServiceContainer.JSON_PROPERTY_SCHEMA_NAME,
  ServiceContainer.JSON_PROPERTY_SERVICE_NAME,
  ServiceContainer.JSON_PROPERTY_SERVICE_STATUS,
  ServiceContainer.JSON_PROPERTY_INSTANCE_ID,
  ServiceContainer.JSON_PROPERTY_INSTANCE_STATUS,
  ServiceContainer.JSON_PROPERTY_CONTAINER_NAME,
  ServiceContainer.JSON_PROPERTY_STATUS,
  ServiceContainer.JSON_PROPERTY_MESSAGE,
  ServiceContainer.JSON_PROPERTY_IMAGE_NAME,
  ServiceContainer.JSON_PROPERTY_IMAGE_DIGEST,
  ServiceContainer.JSON_PROPERTY_RESTART_COUNT,
  ServiceContainer.JSON_PROPERTY_START_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceContainer {
  public static final String JSON_PROPERTY_DATABASE_NAME = "database_name";
  @javax.annotation.Nullable
  private String databaseName;

  public static final String JSON_PROPERTY_SCHEMA_NAME = "schema_name";
  @javax.annotation.Nullable
  private String schemaName;

  public static final String JSON_PROPERTY_SERVICE_NAME = "service_name";
  @javax.annotation.Nullable
  private String serviceName;

  public static final String JSON_PROPERTY_SERVICE_STATUS = "service_status";
  @javax.annotation.Nullable
  private String serviceStatus;

  public static final String JSON_PROPERTY_INSTANCE_ID = "instance_id";
  @javax.annotation.Nullable
  private String instanceId;

  public static final String JSON_PROPERTY_INSTANCE_STATUS = "instance_status";
  @javax.annotation.Nullable
  private String instanceStatus;

  public static final String JSON_PROPERTY_CONTAINER_NAME = "container_name";
  @javax.annotation.Nullable
  private String containerName;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_IMAGE_NAME = "image_name";
  @javax.annotation.Nullable
  private String imageName;

  public static final String JSON_PROPERTY_IMAGE_DIGEST = "image_digest";
  @javax.annotation.Nullable
  private String imageDigest;

  public static final String JSON_PROPERTY_RESTART_COUNT = "restart_count";
  @javax.annotation.Nullable
  private Integer restartCount;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @javax.annotation.Nullable
  private String startTime;

  public ServiceContainer() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ServiceContainer(
    @JsonProperty(JSON_PROPERTY_SERVICE_STATUS) String serviceStatus, 
    @JsonProperty(JSON_PROPERTY_INSTANCE_ID) String instanceId, 
    @JsonProperty(JSON_PROPERTY_INSTANCE_STATUS) String instanceStatus, 
    @JsonProperty(JSON_PROPERTY_CONTAINER_NAME) String containerName, 
    @JsonProperty(JSON_PROPERTY_STATUS) String status, 
    @JsonProperty(JSON_PROPERTY_MESSAGE) String message, 
    @JsonProperty(JSON_PROPERTY_IMAGE_NAME) String imageName, 
    @JsonProperty(JSON_PROPERTY_IMAGE_DIGEST) String imageDigest, 
    @JsonProperty(JSON_PROPERTY_RESTART_COUNT) Integer restartCount, 
    @JsonProperty(JSON_PROPERTY_START_TIME) String startTime
  ) {
    this();
    this.serviceStatus = serviceStatus;
    this.instanceId = instanceId;
    this.instanceStatus = instanceStatus;
    this.containerName = containerName;
    this.status = status;
    this.message = message;
    this.imageName = imageName;
    this.imageDigest = imageDigest;
    this.restartCount = restartCount;
    this.startTime = startTime;
  }

  public ServiceContainer databaseName(@javax.annotation.Nullable String databaseName) {
    
    this.databaseName = databaseName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return databaseName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabaseName() {
    return databaseName;
  }


  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
  }

  public ServiceContainer schemaName(@javax.annotation.Nullable String schemaName) {
    
    this.schemaName = schemaName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return schemaName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaName() {
    return schemaName;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
  }

  public ServiceContainer serviceName(@javax.annotation.Nullable String serviceName) {
    
    this.serviceName = serviceName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return serviceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceName() {
    return serviceName;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
  }

  /**
   * The current status of the service.
   * @return serviceStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceStatus() {
    return serviceStatus;
  }



  /**
   * ID of the service instance (this is the index of the service instance starting from 0).
   * @return instanceId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTANCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceId() {
    return instanceId;
  }



  /**
   * The current status of the service instance.
   * @return instanceStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTANCE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceStatus() {
    return instanceStatus;
  }



  /**
   * Name of the container.
   * @return containerName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTAINER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContainerName() {
    return containerName;
  }



  /**
   * Service container status.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }



  /**
   * Additional clarification about status.
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }



  /**
   * Image name used to create the service container.
   * @return imageName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageName() {
    return imageName;
  }



  /**
   * The unique and immutable identifier representing the image content.
   * @return imageDigest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageDigest() {
    return imageDigest;
  }



  /**
   * Number of times Snowflake restarted the service.
   * @return restartCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESTART_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRestartCount() {
    return restartCount;
  }



  /**
   * Date and time when the container started.
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartTime() {
    return startTime;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceContainer serviceContainer = (ServiceContainer) o;
    return Objects.equals(this.databaseName, serviceContainer.databaseName) &&
        Objects.equals(this.schemaName, serviceContainer.schemaName) &&
        Objects.equals(this.serviceName, serviceContainer.serviceName) &&
        Objects.equals(this.serviceStatus, serviceContainer.serviceStatus) &&
        Objects.equals(this.instanceId, serviceContainer.instanceId) &&
        Objects.equals(this.instanceStatus, serviceContainer.instanceStatus) &&
        Objects.equals(this.containerName, serviceContainer.containerName) &&
        Objects.equals(this.status, serviceContainer.status) &&
        Objects.equals(this.message, serviceContainer.message) &&
        Objects.equals(this.imageName, serviceContainer.imageName) &&
        Objects.equals(this.imageDigest, serviceContainer.imageDigest) &&
        Objects.equals(this.restartCount, serviceContainer.restartCount) &&
        Objects.equals(this.startTime, serviceContainer.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseName, schemaName, serviceName, serviceStatus, instanceId, instanceStatus, containerName, status, message, imageName, imageDigest, restartCount, startTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceContainer {\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    serviceStatus: ").append(toIndentedString(serviceStatus)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    instanceStatus: ").append(toIndentedString(instanceStatus)).append("\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("    imageDigest: ").append(toIndentedString(imageDigest)).append("\n");
    sb.append("    restartCount: ").append(toIndentedString(restartCount)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

