/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceSpecStageFile
 */
@JsonPropertyOrder({
  ServiceSpecStageFile.JSON_PROPERTY_STAGE,
  ServiceSpecStageFile.JSON_PROPERTY_SPEC_FILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
@JsonIgnoreProperties(
  value = "spec_type", // ignore manually set spec_type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the spec_type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "spec_type", visible = true)

public class ServiceSpecStageFile extends ServiceSpec {
  public static final String JSON_PROPERTY_STAGE = "stage";
  @javax.annotation.Nonnull
  private String stage;

  public static final String JSON_PROPERTY_SPEC_FILE = "spec_file";
  @javax.annotation.Nonnull
  private String specFile;

  public ServiceSpecStageFile() {

  }

  public ServiceSpecStageFile stage(@javax.annotation.Nonnull String stage) {
    
    this.stage = stage;
    return this;
  }

  /**
   * Specifies the Snowflake internal stage where the specification file is stored; for example, @tutorial_stage.
   * @return stage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStage() {
    return stage;
  }


  @JsonProperty(value = JSON_PROPERTY_STAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStage(@javax.annotation.Nonnull String stage) {
    this.stage = stage;
  }

  public ServiceSpecStageFile specFile(@javax.annotation.Nonnull String specFile) {
    
    this.specFile = specFile;
    return this;
  }

  /**
   * Specifies the path to the service specification file on the stage; for example, &#39;some-dir/echo_spec.yaml&#39;.
   * @return specFile
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SPEC_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSpecFile() {
    return specFile;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEC_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpecFile(@javax.annotation.Nonnull String specFile) {
    this.specFile = specFile;
  }


  @Override
  public ServiceSpecStageFile specType(@javax.annotation.Nullable String specType) {
    this.setSpecType(specType);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSpecStageFile serviceSpecStageFile = (ServiceSpecStageFile) o;
    return Objects.equals(this.stage, serviceSpecStageFile.stage) &&
        Objects.equals(this.specFile, serviceSpecStageFile.specFile) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stage, specFile, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSpecStageFile {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    specFile: ").append(toIndentedString(specFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

