/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Specifies service specification.
 */
@JsonPropertyOrder({
  ServiceSpec.JSON_PROPERTY_SPEC_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
@JsonIgnoreProperties(
  value = "spec_type", // ignore manually set spec_type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the spec_type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "spec_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = ServiceSpecStageFile.class, name = "from_file"),
  @JsonSubTypes.Type(value = ServiceSpecInlineText.class, name = "from_inline"),
})

public class ServiceSpec {
  public static final String JSON_PROPERTY_SPEC_TYPE = "spec_type";
  // The discriminator does not have Nullability-annotation since it is added during serialization by the @JsonTypeName annotation
  protected String specType;

  public ServiceSpec() {
  }

  public ServiceSpec specType(@javax.annotation.Nullable String specType) {
    
    this.specType = specType;
    return this;
  }

  /**
   * Type of the service specification, can be &#x60;from_file&#x60; or &#x60;from_inline&#x60;.
   * @return specType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEC_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpecType() {
    return specType;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEC_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecType(@javax.annotation.Nullable String specType) {
    this.specType = specType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSpec serviceSpec = (ServiceSpec) o;
    return Objects.equals(this.specType, serviceSpec.specType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSpec {\n");
    sb.append("    specType: ").append(toIndentedString(specType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

