/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceRoleGrantTo
 */
@JsonPropertyOrder({
  ServiceRoleGrantTo.JSON_PROPERTY_CREATED_ON,
  ServiceRoleGrantTo.JSON_PROPERTY_PRIVILEGE,
  ServiceRoleGrantTo.JSON_PROPERTY_GRANTED_ON,
  ServiceRoleGrantTo.JSON_PROPERTY_NAME,
  ServiceRoleGrantTo.JSON_PROPERTY_GRANTED_TO,
  ServiceRoleGrantTo.JSON_PROPERTY_GRANTEE_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceRoleGrantTo {
  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  @javax.annotation.Nullable
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_PRIVILEGE = "privilege";
  @javax.annotation.Nullable
  private String privilege;

  public static final String JSON_PROPERTY_GRANTED_ON = "granted_on";
  @javax.annotation.Nullable
  private String grantedOn;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_GRANTED_TO = "granted_to";
  @javax.annotation.Nullable
  private String grantedTo;

  public static final String JSON_PROPERTY_GRANTEE_NAME = "grantee_name";
  @javax.annotation.Nullable
  private String granteeName;

  public ServiceRoleGrantTo() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ServiceRoleGrantTo(
    @JsonProperty(JSON_PROPERTY_CREATED_ON) OffsetDateTime createdOn, 
    @JsonProperty(JSON_PROPERTY_PRIVILEGE) String privilege, 
    @JsonProperty(JSON_PROPERTY_GRANTED_ON) String grantedOn, 
    @JsonProperty(JSON_PROPERTY_NAME) String name, 
    @JsonProperty(JSON_PROPERTY_GRANTED_TO) String grantedTo, 
    @JsonProperty(JSON_PROPERTY_GRANTEE_NAME) String granteeName
  ) {
    this();
    this.createdOn = createdOn;
    this.privilege = privilege;
    this.grantedOn = grantedOn;
    this.name = name;
    this.grantedTo = grantedTo;
    this.granteeName = granteeName;
  }

  /**
   * Date and time when the grant was created
   * @return createdOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  /**
   * The name of the privilege
   * @return privilege
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVILEGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrivilege() {
    return privilege;
  }



  /**
   * The type of of the securable
   * @return grantedOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrantedOn() {
    return grantedOn;
  }



  /**
   * The name of the securable
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }



  /**
   * The type of the grantee
   * @return grantedTo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTED_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrantedTo() {
    return grantedTo;
  }



  /**
   * The name of the grantee
   * @return granteeName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRANTEE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGranteeName() {
    return granteeName;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRoleGrantTo serviceRoleGrantTo = (ServiceRoleGrantTo) o;
    return Objects.equals(this.createdOn, serviceRoleGrantTo.createdOn) &&
        Objects.equals(this.privilege, serviceRoleGrantTo.privilege) &&
        Objects.equals(this.grantedOn, serviceRoleGrantTo.grantedOn) &&
        Objects.equals(this.name, serviceRoleGrantTo.name) &&
        Objects.equals(this.grantedTo, serviceRoleGrantTo.grantedTo) &&
        Objects.equals(this.granteeName, serviceRoleGrantTo.granteeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, privilege, grantedOn, name, grantedTo, granteeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRoleGrantTo {\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    privilege: ").append(toIndentedString(privilege)).append("\n");
    sb.append("    grantedOn: ").append(toIndentedString(grantedOn)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    grantedTo: ").append(toIndentedString(grantedTo)).append("\n");
    sb.append("    granteeName: ").append(toIndentedString(granteeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

