/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.ServiceSpec;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Service
 */
@JsonPropertyOrder({
  Service.JSON_PROPERTY_NAME,
  Service.JSON_PROPERTY_STATUS,
  Service.JSON_PROPERTY_COMPUTE_POOL,
  Service.JSON_PROPERTY_SPEC,
  Service.JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS,
  Service.JSON_PROPERTY_QUERY_WAREHOUSE,
  Service.JSON_PROPERTY_COMMENT,
  Service.JSON_PROPERTY_IS_ASYNC_JOB,
  Service.JSON_PROPERTY_AUTO_RESUME,
  Service.JSON_PROPERTY_CURRENT_INSTANCES,
  Service.JSON_PROPERTY_TARGET_INSTANCES,
  Service.JSON_PROPERTY_MIN_READY_INSTANCES,
  Service.JSON_PROPERTY_MIN_INSTANCES,
  Service.JSON_PROPERTY_MAX_INSTANCES,
  Service.JSON_PROPERTY_DATABASE_NAME,
  Service.JSON_PROPERTY_SCHEMA_NAME,
  Service.JSON_PROPERTY_OWNER,
  Service.JSON_PROPERTY_DNS_NAME,
  Service.JSON_PROPERTY_CREATED_ON,
  Service.JSON_PROPERTY_UPDATED_ON,
  Service.JSON_PROPERTY_RESUMED_ON,
  Service.JSON_PROPERTY_SUSPENDED_ON,
  Service.JSON_PROPERTY_AUTO_SUSPEND_SECS,
  Service.JSON_PROPERTY_OWNER_ROLE_TYPE,
  Service.JSON_PROPERTY_IS_JOB,
  Service.JSON_PROPERTY_SPEC_DIGEST,
  Service.JSON_PROPERTY_IS_UPGRADING,
  Service.JSON_PROPERTY_MANAGING_OBJECT_DOMAIN,
  Service.JSON_PROPERTY_MANAGING_OBJECT_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class Service {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_COMPUTE_POOL = "compute_pool";
  @javax.annotation.Nonnull
  private String computePool;

  public static final String JSON_PROPERTY_SPEC = "spec";
  @javax.annotation.Nonnull
  private ServiceSpec spec;

  public static final String JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS = "external_access_integrations";
  @javax.annotation.Nullable
  private List<String> externalAccessIntegrations = new ArrayList<>();

  public static final String JSON_PROPERTY_QUERY_WAREHOUSE = "query_warehouse";
  @javax.annotation.Nullable
  private String queryWarehouse;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @javax.annotation.Nullable
  private String comment;

  public static final String JSON_PROPERTY_IS_ASYNC_JOB = "is_async_job";
  @javax.annotation.Nullable
  private Boolean isAsyncJob;

  public static final String JSON_PROPERTY_AUTO_RESUME = "auto_resume";
  @javax.annotation.Nullable
  private Boolean autoResume;

  public static final String JSON_PROPERTY_CURRENT_INSTANCES = "current_instances";
  @javax.annotation.Nullable
  private Integer currentInstances;

  public static final String JSON_PROPERTY_TARGET_INSTANCES = "target_instances";
  @javax.annotation.Nullable
  private Integer targetInstances;

  public static final String JSON_PROPERTY_MIN_READY_INSTANCES = "min_ready_instances";
  @javax.annotation.Nullable
  private Integer minReadyInstances;

  public static final String JSON_PROPERTY_MIN_INSTANCES = "min_instances";
  @javax.annotation.Nullable
  private Integer minInstances;

  public static final String JSON_PROPERTY_MAX_INSTANCES = "max_instances";
  @javax.annotation.Nullable
  private Integer maxInstances;

  public static final String JSON_PROPERTY_DATABASE_NAME = "database_name";
  @javax.annotation.Nullable
  private String databaseName;

  public static final String JSON_PROPERTY_SCHEMA_NAME = "schema_name";
  @javax.annotation.Nullable
  private String schemaName;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private String owner;

  public static final String JSON_PROPERTY_DNS_NAME = "dns_name";
  @javax.annotation.Nullable
  private String dnsName;

  public static final String JSON_PROPERTY_CREATED_ON = "created_on";
  @javax.annotation.Nullable
  private OffsetDateTime createdOn;

  public static final String JSON_PROPERTY_UPDATED_ON = "updated_on";
  @javax.annotation.Nullable
  private OffsetDateTime updatedOn;

  public static final String JSON_PROPERTY_RESUMED_ON = "resumed_on";
  @javax.annotation.Nullable
  private OffsetDateTime resumedOn;

  public static final String JSON_PROPERTY_SUSPENDED_ON = "suspended_on";
  @javax.annotation.Nullable
  private OffsetDateTime suspendedOn;

  public static final String JSON_PROPERTY_AUTO_SUSPEND_SECS = "auto_suspend_secs";
  @javax.annotation.Nullable
  private Long autoSuspendSecs;

  public static final String JSON_PROPERTY_OWNER_ROLE_TYPE = "owner_role_type";
  @javax.annotation.Nullable
  private String ownerRoleType;

  public static final String JSON_PROPERTY_IS_JOB = "is_job";
  @javax.annotation.Nullable
  private Boolean isJob;

  public static final String JSON_PROPERTY_SPEC_DIGEST = "spec_digest";
  @javax.annotation.Nullable
  private String specDigest;

  public static final String JSON_PROPERTY_IS_UPGRADING = "is_upgrading";
  @javax.annotation.Nullable
  private Boolean isUpgrading;

  public static final String JSON_PROPERTY_MANAGING_OBJECT_DOMAIN = "managing_object_domain";
  @javax.annotation.Nullable
  private String managingObjectDomain;

  public static final String JSON_PROPERTY_MANAGING_OBJECT_NAME = "managing_object_name";
  @javax.annotation.Nullable
  private String managingObjectName;

  public Service() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public Service(
    @JsonProperty(JSON_PROPERTY_CURRENT_INSTANCES) Integer currentInstances, 
    @JsonProperty(JSON_PROPERTY_TARGET_INSTANCES) Integer targetInstances, 
    @JsonProperty(JSON_PROPERTY_OWNER) String owner, 
    @JsonProperty(JSON_PROPERTY_DNS_NAME) String dnsName, 
    @JsonProperty(JSON_PROPERTY_CREATED_ON) OffsetDateTime createdOn, 
    @JsonProperty(JSON_PROPERTY_UPDATED_ON) OffsetDateTime updatedOn, 
    @JsonProperty(JSON_PROPERTY_RESUMED_ON) OffsetDateTime resumedOn, 
    @JsonProperty(JSON_PROPERTY_SUSPENDED_ON) OffsetDateTime suspendedOn, 
    @JsonProperty(JSON_PROPERTY_OWNER_ROLE_TYPE) String ownerRoleType, 
    @JsonProperty(JSON_PROPERTY_IS_JOB) Boolean isJob, 
    @JsonProperty(JSON_PROPERTY_SPEC_DIGEST) String specDigest, 
    @JsonProperty(JSON_PROPERTY_IS_UPGRADING) Boolean isUpgrading, 
    @JsonProperty(JSON_PROPERTY_MANAGING_OBJECT_DOMAIN) String managingObjectDomain, 
    @JsonProperty(JSON_PROPERTY_MANAGING_OBJECT_NAME) String managingObjectName
  ) {
    this();
    this.currentInstances = currentInstances;
    this.targetInstances = targetInstances;
    this.owner = owner;
    this.dnsName = dnsName;
    this.createdOn = createdOn;
    this.updatedOn = updatedOn;
    this.resumedOn = resumedOn;
    this.suspendedOn = suspendedOn;
    this.ownerRoleType = ownerRoleType;
    this.isJob = isJob;
    this.specDigest = specDigest;
    this.isUpgrading = isUpgrading;
    this.managingObjectDomain = managingObjectDomain;
    this.managingObjectName = managingObjectName;
  }

  public Service name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public Service status(@javax.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * The current status of the service.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }

  public Service computePool(@javax.annotation.Nonnull String computePool) {
    
    this.computePool = computePool;
    return this;
  }

  /**
   * Specifies the name of the compute pool in your account on which to run the service.
   * @return computePool
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPUTE_POOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getComputePool() {
    return computePool;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPUTE_POOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComputePool(@javax.annotation.Nonnull String computePool) {
    this.computePool = computePool;
  }

  public Service spec(@javax.annotation.Nonnull ServiceSpec spec) {
    
    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   * @return spec
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SPEC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ServiceSpec getSpec() {
    return spec;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEC, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpec(@javax.annotation.Nonnull ServiceSpec spec) {
    this.spec = spec;
  }

  public Service externalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    
    this.externalAccessIntegrations = externalAccessIntegrations;
    return this;
  }

  public Service addExternalAccessIntegrationsItem(String externalAccessIntegrationsItem) {
    if (this.externalAccessIntegrations == null) {
      this.externalAccessIntegrations = new ArrayList<>();
    }
    this.externalAccessIntegrations.add(externalAccessIntegrationsItem);
    return this;
  }

  /**
   * Specifies the names of the external access integrations that allow your service to access external sites.
   * @return externalAccessIntegrations
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExternalAccessIntegrations() {
    return externalAccessIntegrations;
  }


  @JsonProperty(value = JSON_PROPERTY_EXTERNAL_ACCESS_INTEGRATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalAccessIntegrations(@javax.annotation.Nullable List<String> externalAccessIntegrations) {
    this.externalAccessIntegrations = externalAccessIntegrations;
  }

  public Service queryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    
    this.queryWarehouse = queryWarehouse;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return queryWarehouse
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueryWarehouse() {
    return queryWarehouse;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryWarehouse(@javax.annotation.Nullable String queryWarehouse) {
    this.queryWarehouse = queryWarehouse;
  }

  public Service comment(@javax.annotation.Nullable String comment) {
    
    this.comment = comment;
    return this;
  }

  /**
   * Specifies a comment for the service.
   * @return comment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }

  public Service isAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    
    this.isAsyncJob = isAsyncJob;
    return this;
  }

  /**
   * True if the service is an async job service; false otherwise.
   * @return isAsyncJob
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ASYNC_JOB, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsAsyncJob() {
    return isAsyncJob;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ASYNC_JOB, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAsyncJob(@javax.annotation.Nullable Boolean isAsyncJob) {
    this.isAsyncJob = isAsyncJob;
  }

  public Service autoResume(@javax.annotation.Nullable Boolean autoResume) {
    
    this.autoResume = autoResume;
    return this;
  }

  /**
   * Specifies whether to automatically resume a service when a service function or ingress is called.
   * @return autoResume
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_RESUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoResume() {
    return autoResume;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_RESUME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoResume(@javax.annotation.Nullable Boolean autoResume) {
    this.autoResume = autoResume;
  }

  /**
   * The current number of instances for the service.
   * @return currentInstances
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CURRENT_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurrentInstances() {
    return currentInstances;
  }



  /**
   * The target number of service instances that should be running as determined by Snowflake.
   * @return targetInstances
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TARGET_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTargetInstances() {
    return targetInstances;
  }



  public Service minReadyInstances(@javax.annotation.Nullable Integer minReadyInstances) {
    
    this.minReadyInstances = minReadyInstances;
    return this;
  }

  /**
   * The minimum number of ready service instances to declare the service as READY.
   * @return minReadyInstances
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIN_READY_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMinReadyInstances() {
    return minReadyInstances;
  }


  @JsonProperty(value = JSON_PROPERTY_MIN_READY_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinReadyInstances(@javax.annotation.Nullable Integer minReadyInstances) {
    this.minReadyInstances = minReadyInstances;
  }

  public Service minInstances(@javax.annotation.Nullable Integer minInstances) {
    
    this.minInstances = minInstances;
    return this;
  }

  /**
   * Specifies the minimum number of service instances to run.
   * @return minInstances
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIN_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMinInstances() {
    return minInstances;
  }


  @JsonProperty(value = JSON_PROPERTY_MIN_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinInstances(@javax.annotation.Nullable Integer minInstances) {
    this.minInstances = minInstances;
  }

  public Service maxInstances(@javax.annotation.Nullable Integer maxInstances) {
    
    this.maxInstances = maxInstances;
    return this;
  }

  /**
   * Specifies the maximum number of service instances to run.
   * @return maxInstances
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxInstances() {
    return maxInstances;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_INSTANCES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxInstances(@javax.annotation.Nullable Integer maxInstances) {
    this.maxInstances = maxInstances;
  }

  public Service databaseName(@javax.annotation.Nullable String databaseName) {
    
    this.databaseName = databaseName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return databaseName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabaseName() {
    return databaseName;
  }


  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
  }

  public Service schemaName(@javax.annotation.Nullable String schemaName) {
    
    this.schemaName = schemaName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return schemaName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaName() {
    return schemaName;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
  }

  /**
   * Role that owns the service.
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwner() {
    return owner;
  }



  /**
   * Snowflake-assiged DNS name of the service. The DNS name enables service-to-service communications.
   * @return dnsName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DNS_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDnsName() {
    return dnsName;
  }



  /**
   * Timestamp when the service was created.
   * @return createdOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }



  /**
   * Timestamp when the service was last updated.
   * @return updatedOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedOn() {
    return updatedOn;
  }



  /**
   * Timestamp when the service was last resumed.
   * @return resumedOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESUMED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getResumedOn() {
    return resumedOn;
  }



  /**
   * Timestamp when the service was last suspended.
   * @return suspendedOn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUSPENDED_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSuspendedOn() {
    return suspendedOn;
  }



  public Service autoSuspendSecs(@javax.annotation.Nullable Long autoSuspendSecs) {
    
    this.autoSuspendSecs = autoSuspendSecs;
    return this;
  }

  /**
   * Number of seconds of inactivity after which the service will be automatically suspended. The default value is 0 which represents the service will not be automatically suspended.
   * @return autoSuspendSecs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_SUSPEND_SECS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAutoSuspendSecs() {
    return autoSuspendSecs;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_SUSPEND_SECS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoSuspendSecs(@javax.annotation.Nullable Long autoSuspendSecs) {
    this.autoSuspendSecs = autoSuspendSecs;
  }

  /**
   * The role type of the service owner.
   * @return ownerRoleType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER_ROLE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerRoleType() {
    return ownerRoleType;
  }



  /**
   * True if the service is a job service; false otherwise.
   * @return isJob
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_JOB, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsJob() {
    return isJob;
  }



  /**
   * The unique and immutable identifier representing the service spec content.
   * @return specDigest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEC_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpecDigest() {
    return specDigest;
  }



  /**
   * TRUE, if Snowflake is in the process of upgrading the service.
   * @return isUpgrading
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_UPGRADING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsUpgrading() {
    return isUpgrading;
  }



  /**
   * The domain of the managing object (for example, the domain of the notebook that manages the service). NULL if the service is not managed by a Snowflake entity.
   * @return managingObjectDomain
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANAGING_OBJECT_DOMAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManagingObjectDomain() {
    return managingObjectDomain;
  }



  /**
   * The name of the managing object (for example, the name of the notebook that manages the service). NULL if the service is not managed by a Snowflake entity.
   * @return managingObjectName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANAGING_OBJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManagingObjectName() {
    return managingObjectName;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Service service = (Service) o;
    return Objects.equals(this.name, service.name) &&
        Objects.equals(this.status, service.status) &&
        Objects.equals(this.computePool, service.computePool) &&
        Objects.equals(this.spec, service.spec) &&
        Objects.equals(this.externalAccessIntegrations, service.externalAccessIntegrations) &&
        Objects.equals(this.queryWarehouse, service.queryWarehouse) &&
        Objects.equals(this.comment, service.comment) &&
        Objects.equals(this.isAsyncJob, service.isAsyncJob) &&
        Objects.equals(this.autoResume, service.autoResume) &&
        Objects.equals(this.currentInstances, service.currentInstances) &&
        Objects.equals(this.targetInstances, service.targetInstances) &&
        Objects.equals(this.minReadyInstances, service.minReadyInstances) &&
        Objects.equals(this.minInstances, service.minInstances) &&
        Objects.equals(this.maxInstances, service.maxInstances) &&
        Objects.equals(this.databaseName, service.databaseName) &&
        Objects.equals(this.schemaName, service.schemaName) &&
        Objects.equals(this.owner, service.owner) &&
        Objects.equals(this.dnsName, service.dnsName) &&
        Objects.equals(this.createdOn, service.createdOn) &&
        Objects.equals(this.updatedOn, service.updatedOn) &&
        Objects.equals(this.resumedOn, service.resumedOn) &&
        Objects.equals(this.suspendedOn, service.suspendedOn) &&
        Objects.equals(this.autoSuspendSecs, service.autoSuspendSecs) &&
        Objects.equals(this.ownerRoleType, service.ownerRoleType) &&
        Objects.equals(this.isJob, service.isJob) &&
        Objects.equals(this.specDigest, service.specDigest) &&
        Objects.equals(this.isUpgrading, service.isUpgrading) &&
        Objects.equals(this.managingObjectDomain, service.managingObjectDomain) &&
        Objects.equals(this.managingObjectName, service.managingObjectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, computePool, spec, externalAccessIntegrations, queryWarehouse, comment, isAsyncJob, autoResume, currentInstances, targetInstances, minReadyInstances, minInstances, maxInstances, databaseName, schemaName, owner, dnsName, createdOn, updatedOn, resumedOn, suspendedOn, autoSuspendSecs, ownerRoleType, isJob, specDigest, isUpgrading, managingObjectDomain, managingObjectName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Service {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    computePool: ").append(toIndentedString(computePool)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    externalAccessIntegrations: ").append(toIndentedString(externalAccessIntegrations)).append("\n");
    sb.append("    queryWarehouse: ").append(toIndentedString(queryWarehouse)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isAsyncJob: ").append(toIndentedString(isAsyncJob)).append("\n");
    sb.append("    autoResume: ").append(toIndentedString(autoResume)).append("\n");
    sb.append("    currentInstances: ").append(toIndentedString(currentInstances)).append("\n");
    sb.append("    targetInstances: ").append(toIndentedString(targetInstances)).append("\n");
    sb.append("    minReadyInstances: ").append(toIndentedString(minReadyInstances)).append("\n");
    sb.append("    minInstances: ").append(toIndentedString(minInstances)).append("\n");
    sb.append("    maxInstances: ").append(toIndentedString(maxInstances)).append("\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    dnsName: ").append(toIndentedString(dnsName)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    resumedOn: ").append(toIndentedString(resumedOn)).append("\n");
    sb.append("    suspendedOn: ").append(toIndentedString(suspendedOn)).append("\n");
    sb.append("    autoSuspendSecs: ").append(toIndentedString(autoSuspendSecs)).append("\n");
    sb.append("    ownerRoleType: ").append(toIndentedString(ownerRoleType)).append("\n");
    sb.append("    isJob: ").append(toIndentedString(isJob)).append("\n");
    sb.append("    specDigest: ").append(toIndentedString(specDigest)).append("\n");
    sb.append("    isUpgrading: ").append(toIndentedString(isUpgrading)).append("\n");
    sb.append("    managingObjectDomain: ").append(toIndentedString(managingObjectDomain)).append("\n");
    sb.append("    managingObjectName: ").append(toIndentedString(managingObjectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

