/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceEndpoint
 */
@JsonPropertyOrder({
  ServiceEndpoint.JSON_PROPERTY_NAME,
  ServiceEndpoint.JSON_PROPERTY_PORT,
  ServiceEndpoint.JSON_PROPERTY_PORT_RANGE,
  ServiceEndpoint.JSON_PROPERTY_PROTOCOL,
  ServiceEndpoint.JSON_PROPERTY_IS_PUBLIC,
  ServiceEndpoint.JSON_PROPERTY_INGRESS_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceEndpoint {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PORT = "port";
  @javax.annotation.Nullable
  private Integer port;

  public static final String JSON_PROPERTY_PORT_RANGE = "portRange";
  @javax.annotation.Nullable
  private String portRange;

  public static final String JSON_PROPERTY_PROTOCOL = "protocol";
  @javax.annotation.Nullable
  private String protocol = "HTTP";

  public static final String JSON_PROPERTY_IS_PUBLIC = "is_public";
  @javax.annotation.Nullable
  private Boolean isPublic = false;

  public static final String JSON_PROPERTY_INGRESS_URL = "ingress_url";
  @javax.annotation.Nullable
  private String ingressUrl;

  public ServiceEndpoint() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ServiceEndpoint(
    @JsonProperty(JSON_PROPERTY_INGRESS_URL) String ingressUrl
  ) {
    this();
    this.ingressUrl = ingressUrl;
  }

  public ServiceEndpoint name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * User-friendly endpoint name that represents the corresponding port.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceEndpoint port(@javax.annotation.Nullable Integer port) {
    
    this.port = port;
    return this;
  }

  /**
   * The network port the service is listening on. NULL, when portRange is specified.
   * @return port
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPort() {
    return port;
  }


  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@javax.annotation.Nullable Integer port) {
    this.port = port;
  }

  public ServiceEndpoint portRange(@javax.annotation.Nullable String portRange) {
    
    this.portRange = portRange;
    return this;
  }

  /**
   * The network port range the service is listening on. NULL, when port is specified.
   * @return portRange
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORT_RANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPortRange() {
    return portRange;
  }


  @JsonProperty(value = JSON_PROPERTY_PORT_RANGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortRange(@javax.annotation.Nullable String portRange) {
    this.portRange = portRange;
  }

  public ServiceEndpoint protocol(@javax.annotation.Nullable String protocol) {
    
    this.protocol = protocol;
    return this;
  }

  /**
   * Supported network protocol (TCP, HTTP, or HTTPS).
   * @return protocol
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROTOCOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProtocol() {
    return protocol;
  }


  @JsonProperty(value = JSON_PROPERTY_PROTOCOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProtocol(@javax.annotation.Nullable String protocol) {
    this.protocol = protocol;
  }

  public ServiceEndpoint isPublic(@javax.annotation.Nullable Boolean isPublic) {
    
    this.isPublic = isPublic;
    return this;
  }

  /**
   * True, if the endpoint is public, accessible from internet.
   * @return isPublic
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_PUBLIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPublic() {
    return isPublic;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_PUBLIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPublic(@javax.annotation.Nullable Boolean isPublic) {
    this.isPublic = isPublic;
  }

  /**
   * Endpoint URL accessible from the internet.
   * @return ingressUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INGRESS_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIngressUrl() {
    return ingressUrl;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceEndpoint serviceEndpoint = (ServiceEndpoint) o;
    return Objects.equals(this.name, serviceEndpoint.name) &&
        Objects.equals(this.port, serviceEndpoint.port) &&
        Objects.equals(this.portRange, serviceEndpoint.portRange) &&
        Objects.equals(this.protocol, serviceEndpoint.protocol) &&
        Objects.equals(this.isPublic, serviceEndpoint.isPublic) &&
        Objects.equals(this.ingressUrl, serviceEndpoint.ingressUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, port, portRange, protocol, isPublic, ingressUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceEndpoint {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    portRange: ").append(toIndentedString(portRange)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    ingressUrl: ").append(toIndentedString(ingressUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

