/*
 * Snowflake Services API
 * The Snowflake Services API is a REST API that you can use to access, update, and perform certain actions on Services resource in a Snowflake database.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceInstance
 */
@JsonPropertyOrder({
  ServiceInstance.JSON_PROPERTY_DATABASE_NAME,
  ServiceInstance.JSON_PROPERTY_SCHEMA_NAME,
  ServiceInstance.JSON_PROPERTY_SERVICE_NAME,
  ServiceInstance.JSON_PROPERTY_SERVICE_STATUS,
  ServiceInstance.JSON_PROPERTY_INSTANCE_ID,
  ServiceInstance.JSON_PROPERTY_STATUS,
  ServiceInstance.JSON_PROPERTY_SPEC_DIGEST,
  ServiceInstance.JSON_PROPERTY_CREATION_TIME,
  ServiceInstance.JSON_PROPERTY_START_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:25.529847700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class ServiceInstance {
  public static final String JSON_PROPERTY_DATABASE_NAME = "database_name";
  @javax.annotation.Nullable
  private String databaseName;

  public static final String JSON_PROPERTY_SCHEMA_NAME = "schema_name";
  @javax.annotation.Nullable
  private String schemaName;

  public static final String JSON_PROPERTY_SERVICE_NAME = "service_name";
  @javax.annotation.Nullable
  private String serviceName;

  public static final String JSON_PROPERTY_SERVICE_STATUS = "service_status";
  @javax.annotation.Nullable
  private String serviceStatus;

  public static final String JSON_PROPERTY_INSTANCE_ID = "instance_id";
  @javax.annotation.Nullable
  private String instanceId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_SPEC_DIGEST = "spec_digest";
  @javax.annotation.Nullable
  private String specDigest;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation_time";
  @javax.annotation.Nullable
  private String creationTime;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @javax.annotation.Nullable
  private String startTime;

  public ServiceInstance() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public ServiceInstance(
    @JsonProperty(JSON_PROPERTY_SERVICE_STATUS) String serviceStatus, 
    @JsonProperty(JSON_PROPERTY_INSTANCE_ID) String instanceId, 
    @JsonProperty(JSON_PROPERTY_STATUS) String status, 
    @JsonProperty(JSON_PROPERTY_SPEC_DIGEST) String specDigest, 
    @JsonProperty(JSON_PROPERTY_CREATION_TIME) String creationTime, 
    @JsonProperty(JSON_PROPERTY_START_TIME) String startTime
  ) {
    this();
    this.serviceStatus = serviceStatus;
    this.instanceId = instanceId;
    this.status = status;
    this.specDigest = specDigest;
    this.creationTime = creationTime;
    this.startTime = startTime;
  }

  public ServiceInstance databaseName(@javax.annotation.Nullable String databaseName) {
    
    this.databaseName = databaseName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return databaseName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabaseName() {
    return databaseName;
  }


  @JsonProperty(value = JSON_PROPERTY_DATABASE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabaseName(@javax.annotation.Nullable String databaseName) {
    this.databaseName = databaseName;
  }

  public ServiceInstance schemaName(@javax.annotation.Nullable String schemaName) {
    
    this.schemaName = schemaName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return schemaName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchemaName() {
    return schemaName;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchemaName(@javax.annotation.Nullable String schemaName) {
    this.schemaName = schemaName;
  }

  public ServiceInstance serviceName(@javax.annotation.Nullable String serviceName) {
    
    this.serviceName = serviceName;
    return this;
  }

  /**
   * A Snowflake object identifier. If the identifier contains spaces or special characters, the entire string must be enclosed in double quotes. Identifiers enclosed in double quotes are also case-sensitive.
   * @return serviceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceName() {
    return serviceName;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
  }

  /**
   * The current status of the service.
   * @return serviceStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceStatus() {
    return serviceStatus;
  }



  /**
   * ID of the service instance (this is the index of the service instance starting from 0).
   * @return instanceId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSTANCE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInstanceId() {
    return instanceId;
  }



  /**
   * The current status of the service instance.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }



  /**
   * The unique and immutable identifier that represents the service specification content.
   * @return specDigest
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEC_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpecDigest() {
    return specDigest;
  }



  /**
   * The time when Snowflake started creating the service instance.
   * @return creationTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreationTime() {
    return creationTime;
  }



  /**
   * The time when Snowflake acknowledged the service instance is running on a node.
   * @return startTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartTime() {
    return startTime;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInstance serviceInstance = (ServiceInstance) o;
    return Objects.equals(this.databaseName, serviceInstance.databaseName) &&
        Objects.equals(this.schemaName, serviceInstance.schemaName) &&
        Objects.equals(this.serviceName, serviceInstance.serviceName) &&
        Objects.equals(this.serviceStatus, serviceInstance.serviceStatus) &&
        Objects.equals(this.instanceId, serviceInstance.instanceId) &&
        Objects.equals(this.status, serviceInstance.status) &&
        Objects.equals(this.specDigest, serviceInstance.specDigest) &&
        Objects.equals(this.creationTime, serviceInstance.creationTime) &&
        Objects.equals(this.startTime, serviceInstance.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(databaseName, schemaName, serviceName, serviceStatus, instanceId, status, specDigest, creationTime, startTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInstance {\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    schemaName: ").append(toIndentedString(schemaName)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    serviceStatus: ").append(toIndentedString(serviceStatus)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    specDigest: ").append(toIndentedString(specDigest)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

