/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Session parameters that should be set before executing the statement.
 */
@JsonPropertyOrder({
  SubmitStatementRequestParameters.JSON_PROPERTY_TIMEZONE,
  SubmitStatementRequestParameters.JSON_PROPERTY_QUERY_TAG,
  SubmitStatementRequestParameters.JSON_PROPERTY_BINARY_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_DATE_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_TIME_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT,
  SubmitStatementRequestParameters.JSON_PROPERTY_MULTI_STATEMENT_COUNT
})
@JsonTypeName("SubmitStatement_request_parameters")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class SubmitStatementRequestParameters {
  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @javax.annotation.Nullable
  private String timezone;

  public static final String JSON_PROPERTY_QUERY_TAG = "query_tag";
  @javax.annotation.Nullable
  private String queryTag;

  public static final String JSON_PROPERTY_BINARY_OUTPUT_FORMAT = "binary_output_format";
  @javax.annotation.Nullable
  private String binaryOutputFormat;

  public static final String JSON_PROPERTY_DATE_OUTPUT_FORMAT = "date_output_format";
  @javax.annotation.Nullable
  private String dateOutputFormat;

  public static final String JSON_PROPERTY_TIME_OUTPUT_FORMAT = "time_output_format";
  @javax.annotation.Nullable
  private String timeOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT = "timestamp_output_format";
  @javax.annotation.Nullable
  private String timestampOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT = "timestamp_ltz_output_format";
  @javax.annotation.Nullable
  private String timestampLtzOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT = "timestamp_ntz_output_format";
  @javax.annotation.Nullable
  private String timestampNtzOutputFormat;

  public static final String JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT = "timestamp_tz_output_format";
  @javax.annotation.Nullable
  private String timestampTzOutputFormat;

  public static final String JSON_PROPERTY_MULTI_STATEMENT_COUNT = "multi_statement_count";
  @javax.annotation.Nullable
  private Integer multiStatementCount = 1;

  public SubmitStatementRequestParameters() {
  }

  public SubmitStatementRequestParameters timezone(@javax.annotation.Nullable String timezone) {
    
    this.timezone = timezone;
    return this;
  }

  /**
   * Time zone to use when executing the statement.
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimezone() {
    return timezone;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEZONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }

  public SubmitStatementRequestParameters queryTag(@javax.annotation.Nullable String queryTag) {
    
    this.queryTag = queryTag;
    return this;
  }

  /**
   * Query tag that you want to associate with the SQL statement.
   * @return queryTag
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueryTag() {
    return queryTag;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryTag(@javax.annotation.Nullable String queryTag) {
    this.queryTag = queryTag;
  }

  public SubmitStatementRequestParameters binaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    
    this.binaryOutputFormat = binaryOutputFormat;
    return this;
  }

  /**
   * Output format for binary values.
   * @return binaryOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BINARY_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBinaryOutputFormat() {
    return binaryOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_BINARY_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinaryOutputFormat(@javax.annotation.Nullable String binaryOutputFormat) {
    this.binaryOutputFormat = binaryOutputFormat;
  }

  public SubmitStatementRequestParameters dateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    
    this.dateOutputFormat = dateOutputFormat;
    return this;
  }

  /**
   * Output format for DATE values.
   * @return dateOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateOutputFormat() {
    return dateOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOutputFormat(@javax.annotation.Nullable String dateOutputFormat) {
    this.dateOutputFormat = dateOutputFormat;
  }

  public SubmitStatementRequestParameters timeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    
    this.timeOutputFormat = timeOutputFormat;
    return this;
  }

  /**
   * Output format for TIME values.
   * @return timeOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimeOutputFormat() {
    return timeOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeOutputFormat(@javax.annotation.Nullable String timeOutputFormat) {
    this.timeOutputFormat = timeOutputFormat;
  }

  public SubmitStatementRequestParameters timestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    
    this.timestampOutputFormat = timestampOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP values.
   * @return timestampOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampOutputFormat() {
    return timestampOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampOutputFormat(@javax.annotation.Nullable String timestampOutputFormat) {
    this.timestampOutputFormat = timestampOutputFormat;
  }

  public SubmitStatementRequestParameters timestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_LTZ values.
   * @return timestampLtzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampLtzOutputFormat() {
    return timestampLtzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_LTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampLtzOutputFormat(@javax.annotation.Nullable String timestampLtzOutputFormat) {
    this.timestampLtzOutputFormat = timestampLtzOutputFormat;
  }

  public SubmitStatementRequestParameters timestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_NTZ values.
   * @return timestampNtzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampNtzOutputFormat() {
    return timestampNtzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_NTZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampNtzOutputFormat(@javax.annotation.Nullable String timestampNtzOutputFormat) {
    this.timestampNtzOutputFormat = timestampNtzOutputFormat;
  }

  public SubmitStatementRequestParameters timestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    
    this.timestampTzOutputFormat = timestampTzOutputFormat;
    return this;
  }

  /**
   * Output format for TIMESTAMP_TZ values.
   * @return timestampTzOutputFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTimestampTzOutputFormat() {
    return timestampTzOutputFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP_TZ_OUTPUT_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestampTzOutputFormat(@javax.annotation.Nullable String timestampTzOutputFormat) {
    this.timestampTzOutputFormat = timestampTzOutputFormat;
  }

  public SubmitStatementRequestParameters multiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    
    this.multiStatementCount = multiStatementCount;
    return this;
  }

  /**
   * Number of statements to execute when using multi-statement capability. 0 implies variable number of statements. Negative numbers are not allowed.
   * @return multiStatementCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MULTI_STATEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMultiStatementCount() {
    return multiStatementCount;
  }


  @JsonProperty(value = JSON_PROPERTY_MULTI_STATEMENT_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMultiStatementCount(@javax.annotation.Nullable Integer multiStatementCount) {
    this.multiStatementCount = multiStatementCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitStatementRequestParameters submitStatementRequestParameters = (SubmitStatementRequestParameters) o;
    return Objects.equals(this.timezone, submitStatementRequestParameters.timezone) &&
        Objects.equals(this.queryTag, submitStatementRequestParameters.queryTag) &&
        Objects.equals(this.binaryOutputFormat, submitStatementRequestParameters.binaryOutputFormat) &&
        Objects.equals(this.dateOutputFormat, submitStatementRequestParameters.dateOutputFormat) &&
        Objects.equals(this.timeOutputFormat, submitStatementRequestParameters.timeOutputFormat) &&
        Objects.equals(this.timestampOutputFormat, submitStatementRequestParameters.timestampOutputFormat) &&
        Objects.equals(this.timestampLtzOutputFormat, submitStatementRequestParameters.timestampLtzOutputFormat) &&
        Objects.equals(this.timestampNtzOutputFormat, submitStatementRequestParameters.timestampNtzOutputFormat) &&
        Objects.equals(this.timestampTzOutputFormat, submitStatementRequestParameters.timestampTzOutputFormat) &&
        Objects.equals(this.multiStatementCount, submitStatementRequestParameters.multiStatementCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timezone, queryTag, binaryOutputFormat, dateOutputFormat, timeOutputFormat, timestampOutputFormat, timestampLtzOutputFormat, timestampNtzOutputFormat, timestampTzOutputFormat, multiStatementCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitStatementRequestParameters {\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    queryTag: ").append(toIndentedString(queryTag)).append("\n");
    sb.append("    binaryOutputFormat: ").append(toIndentedString(binaryOutputFormat)).append("\n");
    sb.append("    dateOutputFormat: ").append(toIndentedString(dateOutputFormat)).append("\n");
    sb.append("    timeOutputFormat: ").append(toIndentedString(timeOutputFormat)).append("\n");
    sb.append("    timestampOutputFormat: ").append(toIndentedString(timestampOutputFormat)).append("\n");
    sb.append("    timestampLtzOutputFormat: ").append(toIndentedString(timestampLtzOutputFormat)).append("\n");
    sb.append("    timestampNtzOutputFormat: ").append(toIndentedString(timestampNtzOutputFormat)).append("\n");
    sb.append("    timestampTzOutputFormat: ").append(toIndentedString(timestampTzOutputFormat)).append("\n");
    sb.append("    multiStatementCount: ").append(toIndentedString(multiStatementCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

