/*
 * Snowflake SQL API
 * The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.openanalytics.containerproxy.backend.spcs.client.model.SubmitStatementRequestParameters;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubmitStatementRequest
 */
@JsonPropertyOrder({
  SubmitStatementRequest.JSON_PROPERTY_STATEMENT,
  SubmitStatementRequest.JSON_PROPERTY_TIMEOUT,
  SubmitStatementRequest.JSON_PROPERTY_DATABASE,
  SubmitStatementRequest.JSON_PROPERTY_SCHEMA,
  SubmitStatementRequest.JSON_PROPERTY_WAREHOUSE,
  SubmitStatementRequest.JSON_PROPERTY_ROLE,
  SubmitStatementRequest.JSON_PROPERTY_BINDINGS,
  SubmitStatementRequest.JSON_PROPERTY_PARAMETERS
})
@JsonTypeName("SubmitStatement_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:41:35.116838100+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class SubmitStatementRequest {
  public static final String JSON_PROPERTY_STATEMENT = "statement";
  @javax.annotation.Nullable
  private String statement;

  public static final String JSON_PROPERTY_TIMEOUT = "timeout";
  @javax.annotation.Nullable
  private Long timeout;

  public static final String JSON_PROPERTY_DATABASE = "database";
  @javax.annotation.Nullable
  private String database;

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  @javax.annotation.Nullable
  private String schema;

  public static final String JSON_PROPERTY_WAREHOUSE = "warehouse";
  @javax.annotation.Nullable
  private String warehouse;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private String role;

  public static final String JSON_PROPERTY_BINDINGS = "bindings";
  @javax.annotation.Nullable
  private Object bindings;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @javax.annotation.Nullable
  private SubmitStatementRequestParameters parameters;

  public SubmitStatementRequest() {
  }

  public SubmitStatementRequest statement(@javax.annotation.Nullable String statement) {
    
    this.statement = statement;
    return this;
  }

  /**
   * SQL statement or batch of SQL statements to execute. You can specify query, DML and DDL statements. The following statements are not supported: PUT, GET, USE, ALTER SESSION, BEGIN, COMMIT, ROLLBACK, statements that set session variables, and statements that create temporary tables and stages.
   * @return statement
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatement() {
    return statement;
  }


  @JsonProperty(value = JSON_PROPERTY_STATEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatement(@javax.annotation.Nullable String statement) {
    this.statement = statement;
  }

  public SubmitStatementRequest timeout(@javax.annotation.Nullable Long timeout) {
    
    this.timeout = timeout;
    return this;
  }

  /**
   * Timeout in seconds for statement execution. If the execution of a statement takes longer than the specified timeout, the execution is automatically canceled. To set the timeout to the maximum value (604800 seconds), set timeout to 0.
   * minimum: 0
   * @return timeout
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTimeout() {
    return timeout;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMEOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeout(@javax.annotation.Nullable Long timeout) {
    this.timeout = timeout;
  }

  public SubmitStatementRequest database(@javax.annotation.Nullable String database) {
    
    this.database = database;
    return this;
  }

  /**
   * Database in which the statement should be executed. The value in this field is case-sensitive.
   * @return database
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATABASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabase() {
    return database;
  }


  @JsonProperty(value = JSON_PROPERTY_DATABASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabase(@javax.annotation.Nullable String database) {
    this.database = database;
  }

  public SubmitStatementRequest schema(@javax.annotation.Nullable String schema) {
    
    this.schema = schema;
    return this;
  }

  /**
   * Schema in which the statement should be executed. The value in this field is case-sensitive.
   * @return schema
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSchema() {
    return schema;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchema(@javax.annotation.Nullable String schema) {
    this.schema = schema;
  }

  public SubmitStatementRequest warehouse(@javax.annotation.Nullable String warehouse) {
    
    this.warehouse = warehouse;
    return this;
  }

  /**
   * Warehouse to use when executing the statement. The value in this field is case-sensitive.
   * @return warehouse
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWarehouse() {
    return warehouse;
  }


  @JsonProperty(value = JSON_PROPERTY_WAREHOUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarehouse(@javax.annotation.Nullable String warehouse) {
    this.warehouse = warehouse;
  }

  public SubmitStatementRequest role(@javax.annotation.Nullable String role) {
    
    this.role = role;
    return this;
  }

  /**
   * Role to use when executing the statement. The value in this field is case-sensitive.
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@javax.annotation.Nullable String role) {
    this.role = role;
  }

  public SubmitStatementRequest bindings(@javax.annotation.Nullable Object bindings) {
    
    this.bindings = bindings;
    return this;
  }

  /**
   * Values of bind variables in the SQL statement. When executing the statement, Snowflake replaces placeholders (&#39;?&#39; and &#39;:name&#39;) in the statement with these specified values.
   * @return bindings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BINDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getBindings() {
    return bindings;
  }


  @JsonProperty(value = JSON_PROPERTY_BINDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBindings(@javax.annotation.Nullable Object bindings) {
    this.bindings = bindings;
  }

  public SubmitStatementRequest parameters(@javax.annotation.Nullable SubmitStatementRequestParameters parameters) {
    
    this.parameters = parameters;
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SubmitStatementRequestParameters getParameters() {
    return parameters;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParameters(@javax.annotation.Nullable SubmitStatementRequestParameters parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitStatementRequest submitStatementRequest = (SubmitStatementRequest) o;
    return Objects.equals(this.statement, submitStatementRequest.statement) &&
        Objects.equals(this.timeout, submitStatementRequest.timeout) &&
        Objects.equals(this.database, submitStatementRequest.database) &&
        Objects.equals(this.schema, submitStatementRequest.schema) &&
        Objects.equals(this.warehouse, submitStatementRequest.warehouse) &&
        Objects.equals(this.role, submitStatementRequest.role) &&
        Objects.equals(this.bindings, submitStatementRequest.bindings) &&
        Objects.equals(this.parameters, submitStatementRequest.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(statement, timeout, database, schema, warehouse, role, bindings, parameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitStatementRequest {\n");
    sb.append("    statement: ").append(toIndentedString(statement)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    warehouse: ").append(toIndentedString(warehouse)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    bindings: ").append(toIndentedString(bindings)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

