/*
 * Snowflake Warehouse API
 * The Snowflake Warehouse API is a REST API that you can use to access, customize and manage virtual warehouse in a Snowflake account.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Schema for a request in progress response returned by the server.
 */
@JsonPropertyOrder({
  SuccessAcceptedResponse.JSON_PROPERTY_CODE,
  SuccessAcceptedResponse.JSON_PROPERTY_MESSAGE,
  SuccessAcceptedResponse.JSON_PROPERTY_RESULT_HANDLER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:42:29.597406700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class SuccessAcceptedResponse {
  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_RESULT_HANDLER = "resultHandler";
  @javax.annotation.Nullable
  private String resultHandler;

  public SuccessAcceptedResponse() {
  }

  public SuccessAcceptedResponse code(@javax.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Message code returned by the server.
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }

  public SuccessAcceptedResponse message(@javax.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Message returned by the server
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }

  public SuccessAcceptedResponse resultHandler(@javax.annotation.Nullable String resultHandler) {
    
    this.resultHandler = resultHandler;
    return this;
  }

  /**
   * Opaque result ID used for checking for request completion through one or more subsequent completion check operations.
   * @return resultHandler
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULT_HANDLER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultHandler() {
    return resultHandler;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT_HANDLER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultHandler(@javax.annotation.Nullable String resultHandler) {
    this.resultHandler = resultHandler;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccessAcceptedResponse successAcceptedResponse = (SuccessAcceptedResponse) o;
    return Objects.equals(this.code, successAcceptedResponse.code) &&
        Objects.equals(this.message, successAcceptedResponse.message) &&
        Objects.equals(this.resultHandler, successAcceptedResponse.resultHandler);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, resultHandler);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccessAcceptedResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    resultHandler: ").append(toIndentedString(resultHandler)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

