/*
 * Snowflake Warehouse API
 * The Snowflake Warehouse API is a REST API that you can use to access, customize and manage virtual warehouse in a Snowflake account.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@snowflake.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.openanalytics.containerproxy.backend.spcs.client.auth;

import org.springframework.http.HttpHeaders;
import org.springframework.util.MultiValueMap;

import java.util.function.Supplier;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-02T16:42:29.597406700+08:00[Australia/Perth]", comments = "Generator version: 7.17.0")
public class HttpBearerAuth implements Authentication {
    private final String scheme;
    private String bearerToken;
    /** Optional: when set, token is resolved per request (e.g. for SPCS session token file). */
    private Supplier<String> bearerTokenSupplier;

    public HttpBearerAuth(String scheme) {
        this.scheme = scheme;
    }

    public String getBearerToken() {
        return bearerToken;
    }

    public void setBearerToken(String bearerToken) {
        this.bearerToken = bearerToken;
        this.bearerTokenSupplier = null;
    }

    /**
     * Set a supplier so the token is resolved on each request.
     * Use for SPCS session token (file can be updated) or keypair JWT (refresh on expiry).
     */
    public void setBearerToken(Supplier<String> bearerTokenSupplier) {
        this.bearerTokenSupplier = bearerTokenSupplier;
        this.bearerToken = null;
    }

    @Override
    public void applyToParams(MultiValueMap<String, String> queryParams, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams) {
        String token = bearerTokenSupplier != null ? bearerTokenSupplier.get() : bearerToken;
        if (token == null) {
            return;
        }
        headerParams.add(HttpHeaders.AUTHORIZATION, (scheme != null ? upperCaseBearer(scheme) + " " : "") + token);
    }

    private static String upperCaseBearer(String scheme) {
        return ("bearer".equalsIgnoreCase(scheme)) ? "Bearer" : scheme;
    }

}
